### ISSUE TITLE
иправить проблему в навигации

### ISSUE THREAD

**Issue by gpavlov1** [dimacodeit/react-twitter-clone#56]
на главной станице при нажатии эксплоер и т.д идет смещение меню в центр
![CvFibliJ5QkSlBY4Dy6Jn9oKwuNq-n4MB0K83iLfK9ldP_FB8Q8CBT_R-Alby7fgVXkhUvMvtKHGZ3jbd3eRfrqB](https://user-images.githubusercontent.com/105434873/169377568-be968012-defb-4b7a-9e2e-585006ff9421.jpg)
р

**Comment by dimacodeit** [comment]
@gpavlov1 готово
